version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./volumes:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=court_crawler

  web:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    depends_on:
      - db
