version: '3'

services:
  postgres:
    image: postgres:11.5
    volumes:
      - "./volumes:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=court_crawler
      - POSTGRES_HOST=0.0.0.0

  web:
    build: .
    ports:
      - "3333:3333"
    command: ["python3", "modules/api/router.py"]
    volumes:
      - .:/app
    depends_on:
      - postgres
