version: '3'

services:
  postgres:
    image: postgres:10.2
    ports:
      - "5433:5432"
    volumes:
      - ./.volumes:/var/lib/postgresql/db_data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=court_crawler
      # - POSTGRES_HOST=0.0.0.0

  web:
    build: .
    volumes:
      - .:/backend-crawler
    ports:
      - "3333:3333"
    command: python3 modules/api/router.py
    depends_on:
      - postgres
